runtime: java17
instance_class: F2

env_variables:
  BUCKET_NAME: "milkteacloud"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

entrypoint: java -jar /home/g21110915/MilkTea/target/project-1.0.war
